version: '3.8'
networks:
  net:
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./.env
    hostname: db
    container_name: db
    expose:
      - 3306
    networks:
      - net
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql_dump:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  redis:
    image: redis
    hostname: redis
    container_name: redis
    expose:
      - 6379
    volumes:
      - ./redis:/data
  server:
    volumes:
      - ./server:/server
    build: ./server/
    command: "hypercorn app:asgi_app --bind 0.0.0.0:8000"
    networks:
      - net
    ports:
      - 8000:8000
    hostname: server
    container_name: server
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./.env